version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017/blogify
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"