apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depolyment
  namespace: blogapp
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog

  template:
    metadata:
      namespace: blogapp
      labels:
        app: blog
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0.0
          ports: 
            - containerPort: 27017