apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: blogapp
  labels:
    app: blog
spec:
  seletor:
    app: blog
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP