apiVersion: v1
kind: Service
metadata:
  name: blogapp-svc
  namespace: blogapp
  labels:
    app: blog
spec:
  selector:
    app: blog
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP